development:
  adapter: postgresql
  encoding: unicode
  database: health_tracker_react_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: health_tracker_react_test
  pool: 5
